/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "FlipSentences": {
    name: "FlipSentences",
    description: "Animated rotating sentences component",
    type: "registry:example",
    files: [{
      path: "src/registry/flip-sentences/flip-sentences.tsx",
      type: "registry:file",
    }],
    component: React.lazy(() => import("@/registry/flip-sentences/flip-sentences.tsx")),
  },
}